// <auto-generated />
using System;
using BE.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Infrastructure.Migrations
{
    [DbContext(typeof(BEContext))]
    [Migration("20250916051942_cambio_logica_proveedor_producto")]
    partial class cambio_logica_proveedor_producto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Actualizado")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("es_activo");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Actualizado")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("es_activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Actualizado")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("es_activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SupplierProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Actualizado")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("es_activo");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("lot_number");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_products");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_products_supplier_id");

                    b.HasIndex("ProductId", "SupplierId", "LotNumber")
                        .HasDatabaseName("ix_supplier_products_product_id_supplier_id_lot_number");

                    b.ToTable("supplier_products", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.SupplierProduct", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_products_products_product_id");

                    b.HasOne("MyApp.Domain.Entities.Supplier", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_products_suppliers_supplier_id");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Product", b =>
                {
                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
